# Copyright 2022-2023 Hewlett Packard Enterprise Development LP
name: Acceptance Tests(including cluster create test)

on:
  schedule:
    # Runs every night at 1:30 am
    - cron: "30 1 * * *"
jobs:
  ci:
    runs-on: self-hosted
    strategy:
      matrix:
        go: [ '1.21' ]
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Install packages
        run: go install github.com/nomad-software/vend@v1.0.3

      - name: Run acceptance tests
        env:
          HPEGL_TENANT_ID:  ${{ secrets.HPEGL_TENANT_ID }}
          HPEGL_USER_ID: ${{ secrets.HPEGL_USER_ID }}
          HPEGL_USER_SECRET: ${{ secrets.HPEGL_USER_SECRET }}
          HPEGL_IAM_SERVICE_URL: ${{ secrets.HPEGL_IAM_SERVICE_URL }}
          TF_VAR_HPEGL_SPACE: ${{ secrets.TF_VAR_HPEGL_SPACE }}
        run: make acceptance
